# Generated by Django 5.0 on 2024-12-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataDiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('usia', models.IntegerField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('status_perkawinan', models.CharField(choices=[('Belum berkeluarga', 'Belum berkeluarga'), ('Duda', 'Duda'), ('Janda', 'Janda'), ('Berkeluarga', 'Berkeluarga')], max_length=20)),
                ('pendidikan', models.CharField(choices=[('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('Diploma', 'Diploma'), ('Sarjana', 'Sarjana'), ('Pascasarjana', 'Pascasarjana')], max_length=20)),
                ('tempat_tinggal', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.section')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='base.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('SS', 'Sangat Setuju'), ('S', 'Setuju'), ('R', 'Ragu-Ragu'), ('TS', 'Tidak Setuju'), ('STS', 'Sangat Tidak Setuju')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subquestion')),
            ],
        ),
    ]
