# Generated by Django 5.2.4 on 2025-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_irkresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadiri',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=15),
        ),
        migrations.AlterField(
            model_name='datadiri',
            name='pekerjaan',
            field=models.CharField(choices=[('ASN/TNI/Polri/Pegawai BUMN', 'ASN/TNI/Polri/Pegawai BUMN'), ('Karyawan swasta/Profesional non PNS', 'Karyawan swasta/Profesional non PNS (dokter, notaris, pengacara, konsultan, dosen, arsitek)'), ('Pengusaha/Pedagang/Kontraktor', 'Pengusaha/Pedagang/Kontraktor'), ('Buruh harian/Ojek Online/Petani/Nelayan/Peternak/Freelancer', 'Buruh harian/Ojek Online/Petani/Nelayan/Peternak/Freelancer'), ('IRT/Pelajar/Mahasiswa/Belum (Tidak) Bekerja', 'IRT/Pelajar/Mahasiswa/Belum (Tidak) Bekerja')], max_length=120),
        ),
        migrations.AlterField(
            model_name='datadiri',
            name='status_perkawinan',
            field=models.CharField(choices=[('Belum berkeluarga', 'Belum berkeluarga'), ('Duda', 'Duda'), ('Janda', 'Janda'), ('Berkeluarga', 'Berkeluarga')], default='Belum berkeluarga', max_length=20),
        ),
        migrations.AlterField(
            model_name='irkresult',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='irkresult',
            name='irk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
