# Generated by Django 5.2.4 on 2025-08-19 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_irkresult_created_at_alter_datadiri_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadiri',
            name='pekerjaan',
            field=models.CharField(choices=[('ASN/TNI/Polri/Pegawai BUMN', 'ASN/TNI/Polri/Pegawai BUMN'), ('Swasta', 'Karyawan swasta/Profesional non PNS (dokter, notaris, pengacara, konsultan, dosen, arsitek)'), ('Pengusaha', 'Pengusaha/Pedagang/Kontraktor'), ('Buruh/Freelancer', 'Buruh harian/Ojek Online/Petani/Nelayan/Peternak/Freelancer'), ('IRT/Pelajar/Mahasiswa', 'IRT/Pelajar/Mahasiswa/Belum (Tidak) Bekerja')], max_length=120),
        ),
        migrations.AlterField(
            model_name='irkresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
