# Generated by Django 5.2.4 on 2025-08-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_datadiri_pekerjaan_alter_irkresult_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irkresult',
            options={'ordering': ['-created_at']},
        ),
    ]
