# Generated by Django 5.2.4 on 2025-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_irkresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irkresult',
            options={},
        ),
        migrations.AddField(
            model_name='irkresult',
            name='nama',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datadiri',
            name='pekerjaan',
            field=models.CharField(choices=[('ASN/TNI/Polri/Pegawai BUMN', 'ASN/TNI/Polri/Pegawai BUMN'), ('Karyawan swasta/Profesional non PNS', 'Karyawan swasta/Profesional non PNS (dokter, notaris, pengacara, konsultan, dosen, arsitek)'), ('Pengusaha/Pedagang/Kontraktor', 'Pengusaha/Pedagang/Kontraktor'), ('Buruh harian/Ojek Online/Petani/Nelayan/Peternak/Freelancer', 'Buruh harian/Ojek Online/Petani/Nelayan/Peternak/Freelancer'), ('IRT/Pelajar/Mahasiswa/Belum (Tidak) Bekerja', 'IRT/Pelajar/Mahasiswa/Belum (Tidak) Bekerja')], max_length=120),
        ),
        migrations.AlterField(
            model_name='irkresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
