# Generated by Django 5.2.4 on 2025-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_datadiri_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadiri',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datadiri',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
