# Generated by Django 5.2.4 on 2025-09-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_datadiri_latitude_datadiri_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='datadiri',
            old_name='kabupaten_kota',
            new_name='alamat',
        ),
        migrations.RemoveField(
            model_name='datadiri',
            name='tempat_tinggal',
        ),
        migrations.AddField(
            model_name='datadiri',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.desa'),
        ),
        migrations.AddField(
            model_name='desa',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desa_list', to='base.kecamatan'),
        ),
        migrations.AddField(
            model_name='datadiri',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kecamatan'),
        ),
    ]
