# Generated by Django 5.2.4 on 2025-09-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_desa_kecamatan_rename_kabupaten_kota_datadiri_alamat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irkresult',
            options={'ordering': ['-id']},
        ),
    ]
