# Generated by Django 5.2.4 on 2025-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_irkresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='irkresult',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
