# Generated by Django 5.2.4 on 2025-09-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_irkresult_pekerjaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irkresult',
            name='pekerjaan',
        ),
    ]
