# Generated by Django 5.2.4 on 2025-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_irkresult_pekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='irkresult',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
