# Generated by Django 5.2.6 on 2025-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_irkresult_pekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='irkresult',
            name='desa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='irkresult',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
